name: Deploy Telegram Bot

on:
  workflow_dispatch:
  schedule:
    # Runs daily at 10:25 PM Toronto time (3:25 AM UTC in winter, 2:25 AM UTC in summer)
    - cron: '25 3 * 11,12,1,2,3 *' # Winter time (November - March)
    - cron: '25 2 * 4,5,6,7,8,9,10 *' # Summer time (April - October)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build project
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          PASSWORD_HASH: ${{ secrets.PASSWORD_HASH }}
          DB_PATH: ${{ secrets.DB_PATH }}
        run: npm run build

      # Install sshpass to handle password-based SSH
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # Install rsync
      - name: Install rsync
        run: sudo apt-get install -y rsync

      # Copy built files to the server using scp and sshpass
      - name: Transfer built files via SSH
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sshpass -p "$SERVER_PASSWORD" rsync -avz --exclude 'sessions' -e "ssh -o StrictHostKeyChecking=no" dist/ $SERVER_USER@$SERVER_IP:/root/telegram_bot/

      # Restart PM2 on the server
      - name: Reload bot on the server using pm2
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          PASSWORD_HASH: ${{ secrets.PASSWORD_HASH }}
          DB_PATH: ${{ secrets.DB_PATH }}
        run: |
          sshpass -p "$SERVER_PASSWORD" ssh $SERVER_USER@$SERVER_IP "
            cd $PROJECT_DIR &&
            TELEGRAM_TOKEN='$TELEGRAM_TOKEN' PASSWORD_HASH='$PASSWORD_HASH' DB_PATH='$DB_PATH' pm2 restart tbot --update-env
          "
