name: Post-Restart Deploy

on:
  schedule:
    # Runs every Saturday at 5:05 PM UTC (5 minutes after server restart)
    - cron: '5 17 * * 6'

jobs:
  trigger_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy.yml',
              ref: 'main'
            });
