name: Deploy at 10 PM Toronto Time

on:
  schedule:
    # Runs daily at 10:07 PM ET during winter time (3:07 AM UTC)
    - cron: '7 3 * 11,12,1,2,3 *'

jobs:
  trigger_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy.yml',
              ref: 'main'
            });
