name: Deploy at 10 PM Toronto Time

on:
  schedule:
    # Runs daily at 10:03 PM Toronto time (3:03 AM UTC) during Standard Time (November - March)
    - cron: '3 3 * 11,12,1,2,3 *'
    # Runs daily at 10:03 PM Toronto time (2:03 AM UTC) during Daylight Saving Time (April - October)
    - cron: '3 2 * 4,5,6,7,8,9,10 *'

jobs:
  trigger_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy.yml',
              ref: 'main'
            });
