name: Deploy at 10 PM Toronto Time

on:
  schedule:
    # Runs at 10:00 PM Toronto time (3:00 AM UTC Sunday) during Standard Time (November - March)
    - cron: '0 3 * * 0'
    # Runs at 10:00 PM Toronto time (2:00 AM UTC Sunday) during Daylight Saving Time (April - October)
    - cron: '0 2 * * 0'

jobs:
  trigger_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Workflow
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'deploy.yml',
              ref: 'main'
            });
